In [2]:
import tensorflow as tf

# List all physical GPU devices detected by the system
gpus = tf.config.list_physical_devices('GPU')
print("Num GPUs Available: ", len(gpus))
print("GPU Details: ", gpus)

Num GPUs Available:  1
GPU Details:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

# It is Muti-class Classification

In [3]:
df = pd.read_csv('/kaggle/input/datasets/atharvaingle/crop-recommendation-dataset/Crop_recommendation.csv')

* N - ratio of Nitrogen content in soil
* P - ratio of Phosphorous content in soil
* K - ratio of Potassium content in soil
* temperature - temperature in degree Celsius
* humidity - relative humidity in %
* ph - ph value of the soil
* rainfall - rainfall in mm
* label - which crop is recommended/planted based on the given conditions.

In [4]:
df

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [5]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['label']= encoder.fit_transform(df['label'])

In [7]:
df['label'].value_counts().sort_index()

label
0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
Name: count, dtype: int64

In [8]:
X = df.iloc[:,:-1]
X

        N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [9]:
y = df.iloc[:,-1]
y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: label, Length: 2200, dtype: int64

In [10]:
df

        N   P   K  temperature   humidity        ph    rainfall  label
0      90  42  43    20.879744  82.002744  6.502985  202.935536     20
1      85  58  41    21.770462  80.319644  7.038096  226.655537     20
2      60  55  44    23.004459  82.320763  7.840207  263.964248     20
3      74  35  40    26.491096  80.158363  6.980401  242.864034     20
4      78  42  42    20.130175  81.604873  7.628473  262.717340     20
...   ...  ..  ..          ...        ...       ...         ...    ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507      5
2196   99  15  27    27.417112  56.636362  6.086922  127.924610      5
2197  118  33  30    24.131797  67.225123  6.362608  173.322839      5
2198  117  32  34    26.272418  52.127394  6.758793  127.175293      5
2199  104  18  30    23.603016  60.396475  6.779833  140.937041      5

[2200 rows x 8 columns]

In [11]:
# **This is the code to show that which label is given to which catorgical data** 

label_mapping = dict(zip(encoder.classes_, range(len(encoder.classes_))))
print(label_mapping)

{'apple': 0, 'banana': 1, 'blackgram': 2, 'chickpea': 3, 'coconut': 4, 'coffee': 5, 'cotton': 6, 'grapes': 7, 'jute': 8, 'kidneybeans': 9, 'lentil': 10, 'maize': 11, 'mango': 12, 'mothbeans': 13, 'mungbean': 14, 'muskmelon': 15, 'orange': 16, 'papaya': 17, 'pigeonpeas': 18, 'pomegranate': 19, 'rice': 20, 'watermelon': 21}

In [12]:
from sklearn.model_selection import train_test_split
#random_state means lock the data every time take the same data,any number can give 42 is just popular
# Split data: 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X_train.shape

(1760, 7)

In [15]:
X_train_scaled.shape

(1760, 7)

In [16]:
y_train

1656    16
752      2
892     10
1041     1
1179    12
        ..
1638    16
1095     1
1130    12
1294     7
860     10
Name: label, Length: 1760, dtype: int64

In [17]:
print(y.nunique()) # y have 22 multi-classes

22

# General model Training manually

In [18]:
import tensorflow
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras import Sequential

**After the dense we write the units=64 units means number of layer we can write and not this is optinal but written the units give me clear picture**

In [19]:
units=model = Sequential()
model.add(Input(shape=(7,)))
model.add(Dense(units=12,activation='relu'))
model.add(Dense(units=22,activation='softmax')) # it is multi-classification so use Softmax activation 
# it has 22 label or output including 0

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788713432.341946      58 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15511 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

In [20]:
model.compile(loss='sparse_categorical_crossentropy',optimizer ='adam',metrics=['accuracy'] )

In [21]:
df

        N   P   K  temperature   humidity        ph    rainfall  label
0      90  42  43    20.879744  82.002744  6.502985  202.935536     20
1      85  58  41    21.770462  80.319644  7.038096  226.655537     20
2      60  55  44    23.004459  82.320763  7.840207  263.964248     20
3      74  35  40    26.491096  80.158363  6.980401  242.864034     20
4      78  42  42    20.130175  81.604873  7.628473  262.717340     20
...   ...  ..  ..          ...        ...       ...         ...    ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507      5
2196   99  15  27    27.417112  56.636362  6.086922  127.924610      5
2197  118  33  30    24.131797  67.225123  6.362608  173.322839      5
2198  117  32  34    26.272418  52.127394  6.758793  127.175293      5
2199  104  18  30    23.603016  60.396475  6.779833  140.937041      5

[2200 rows x 8 columns]

In [22]:
model.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))
# validation_data: internally predicts on X_test 
# and compares predictions with y_test to calculate val_accuracy and val_loss
# validation_data = model.predict(X_test) and accuracyscore(y_test,y_pred)

Epoch 1/20
52/55 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0593 - loss: 3.0883

I0000 00:00:1788713435.071646     128 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

55/55 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.0653 - loss: 3.0390 - val_accuracy: 0.0682 - val_loss: 48.1363
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0966 - loss: 2.8548 - val_accuracy: 0.0773 - val_loss: 49.1955
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1892 - loss: 2.6720 - val_accuracy: 0.0886 - val_loss: 54.5830
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2716 - loss: 2.4730 - val_accuracy: 0.0591 - val_loss: 62.6548
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3159 - loss: 2.2576 - val_accuracy: 0.0750 - val_loss: 69.1236
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3977 - loss: 2.0363 - val_accuracy: 0.0795 - val_loss: 76.5535
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4994 - loss: 1.8210 - val_accuracy: 0.1068 - val_loss: 85.7734
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5949 - loss: 1.6206 - val_accuracy: 0.1273 - val_loss: 94.6935
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6744 - loss: 1.4378 - val_accuracy: 0.1227 - val_loss: 105.3384
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7267 - loss: 1.2768 - val_accuracy: 0.1227 - val_loss: 116.5146
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 1.1360 - val_accuracy: 0.1227 - val_loss: 126.2639
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7966 - loss: 1.0156 - val_accuracy: 0.1227 - val_loss: 138.9591
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8477 - loss: 0.9128 - val_accuracy: 0.1227 - val_loss: 149.2340
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8602 - loss: 0.8260 - val_accuracy: 0.1227 - val_loss: 159.9322
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8790 - loss: 0.7517 - val_accuracy: 0.1205 - val_loss: 171.1200
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8955 - loss: 0.6887 - val_accuracy: 0.1136 - val_loss: 184.1353
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9000 - loss: 0.6356 - val_accuracy: 0.0977 - val_loss: 195.1527
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9051 - loss: 0.5883 - val_accuracy: 0.0932 - val_loss: 205.3270
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9176 - loss: 0.5484 - val_accuracy: 0.0909 - val_loss: 215.0599
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9176 - loss: 0.5128 - val_accuracy: 0.0909 - val_loss: 224.4506

# val_accuracy = 09%

# Now we find the best paramter with keras tuner one by one then all 
* 1. how to select appropriate optimizer
* 2. No, of nodes in a layer
* 3. how to select no. of layers
* 4. All in all one model

# And our Objective is to find the best model that have max val_accuracy beacuse it is test unseen data

In [23]:
# Install the keras tuner 
! pip install keras-tuner --upgrade

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.5)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [24]:
import keras_tuner as kt

**The Sequence**

⭐ **B = Build → T = Tune → S = Search → E = Extract → R = Retrain**

**First B = Build → T = Tune → S = Search 😁 Then  E = Extract → R = Retrain**

# With RandomSearch tuner

# First We find the Best Optimizer

⭐**First, we define a `build_model` function that creates and returns our neural network model. The function takes a parameter `hp`, which represents the hyperparameters provided by Keras Tuner.**

**To allow Keras Tuner to choose the optimizer, we use `hp.Choice()`. Inside `hp.Choice()`, we provide the name of the hyperparameter (`'Optimizer'`) and a list of optimizers that the tuner can choose from.**

**Keras Tuner will then select an optimizer from this list and use it to compile the model. Different trials can use different optimizers, allowing the tuner to compare their performance and find the best one.** ⬇️

# Build

In [25]:
def build_model(hp):
    model_1 = Sequential()
    model_1.add(Input(shape=(7,))) # Input 
    
    model_1.add(Dense(12,activation='relu')) #  hidden layer
    
    model_1.add(Dense(22,activation='softmax')) # Last neurons
    
    optimizers = hp.Choice('Optimizer',[ "adam","adamw","rmsprop","adagrad","adadelta","adamax","nadam","adafactor","lion","lamb","muon","ftrl"])
    
    model_1.compile(optimizer=optimizers,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

    return model_1

# Tune

⭐ **`RandomSearch` means that Keras Tuner randomly searches through different combinations of hyperparameters.**

**Here, we define the `hypermodel` using our `build_model` function. The `objective` specifies what we want to improve or maximize — here, `val_accuracy` means we want to find the hyperparameter combination that gives the highest validation accuracy.**

**`max_trials` specifies how many different hyperparameter combinations Keras Tuner should try. For example, `max_trials=15` means the tuner can run up to 15 different trials.**

**If we want to save the results of the search, we can use `directory` to specify the main folder where the results will be stored and `project_name` to create a separate folder for this particular tuning project.**

**`overwrite=True` means that if the same project already exists, its previous results will be overwritten and a new search will start.** ⬇️

**Tuner = the thing that decides which hyperparameter combinations to try, runs the trials, and keeps track of their performance**

In [26]:
tuner_o = kt.RandomSearch(hypermodel=build_model,objective="val_accuracy",max_trials=15 ,directory="my_dir",
    project_name="helloworld",overwrite=True,)

**You can see the summary of your search space**

💫(optional) **`tuner.search_space_summary()` is used to display a summary of the search space defined in the `build_model` function. It shows all the hyperparameters that Keras Tuner can change during the search, along with their possible values or ranges.**

**In our case, it will show the `Optimizer` hyperparameter and the list of optimizers that Keras Tuner can choose from.** ⬇️

In [27]:
tuner_o.search_space_summary()

Search space summary
Default search space size: 1
Optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'adamw', 'rmsprop', 'adagrad', 'adadelta', 'adamax', 'nadam', 'adafactor', 'lion', 'lamb', 'muon', 'ftrl'], 'ordered': False}

# Search

⭐ **`tuner.search()` is used to start the hyperparameter tuning process.**

**Here, we provide `X_train` and `y_train` as the training data. `epochs=20` means that each trial will train the model for a maximum of 20 epochs. `validation_data=(X_test, y_test)` is used to evaluate the model on the validation data after each epoch.**

**Keras Tuner will run different trials, where each trial uses a different hyperparameter combination, and compare their performance based on the objective we defined earlier, such as `val_accuracy`.**

**In our example, because we have `max_trials=15`, Keras Tuner can try up to 15 different optimizer choices, with each trial training for up to 20 epochs.** ⬇️

**Training here**

In [28]:
tuner_o.search(X_train_scaled, y_train, epochs=20, validation_data=(X_test, y_test))

Trial 11 Complete [00h 00m 00s]

Best val_accuracy So Far: 0.22727273404598236
Total elapsed time: 00h 00m 59s

In [79]:
tuner_o.results_summary()

Results summary
Results in my_dir/helloworld
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 04 summary
Hyperparameters:
Optimizer: adafactor
Score: 0.22727273404598236

Trial 07 summary
Hyperparameters:
Optimizer: nadam
Score: 0.18863636255264282

Trial 06 summary
Hyperparameters:
Optimizer: lion
Score: 0.18409091234207153

Trial 02 summary
Hyperparameters:
Optimizer: adamw
Score: 0.1818181872367859

Trial 05 summary
Hyperparameters:
Optimizer: rmsprop
Score: 0.16363635659217834

Trial 03 summary
Hyperparameters:
Optimizer: adamax
Score: 0.1409090906381607

Trial 08 summary
Hyperparameters:
Optimizer: adam
Score: 0.13636364042758942

Trial 01 summary
Hyperparameters:
Optimizer: ftrl
Score: 0.07954545319080353

Trial 00 summary
Hyperparameters:
Optimizer: adagrad
Score: 0.036363635212183

Trial 09 summary
Hyperparameters:
Optimizer: lamb
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/keras_tuner/src/engine/tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/keras_tuner/src/engine/tuner.py", line 232, in _build_and_fit_model
    model = self._try_build(hp)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/keras_tuner/src/engine/tuner.py", line 164, in _try_build
    model = self._build_hypermodel(hp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/keras_tuner/src/engine/tuner.py", line 155, in _build_hypermodel
    model = self.hypermodel.build(hp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_58/2377753447.py", line 11, in build_model
    model_1.compile(optimizer=optimizers,loss='sparse_categorical_crossentropy',metrics=['accuracy'])
  File "/usr/local/lib/python3.12/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.12/dist-packages/keras/src/optimizers/__init__.py", line 98, in get
    raise ValueError(f"Could not interpret optimizer identifier: {identifier}")
ValueError: Could not interpret optimizer identifier: lamb

⭐ **We see which is the best hyperparamter with this small code**

In [30]:
tuner_o.get_best_hyperparameters()[0].values

{'Optimizer': 'adafactor'}

# Extract

⭐ **Extract the Best Optimizer Model**

**We use `tuner.get_best_models(num_models=1)[0]` to extract the best-performing model found during the hyperparameter search.**

**`num_models=1` tells Keras Tuner that we want only the best model, and `[0]` selects that first model from the returned list.**

**Then, `best_model_optimizer.summary()` displays the architecture and details of the selected best model.**

In [31]:
best_model_optimizer = tuner_o.get_best_models(num_models=1)[0]
best_model_optimizer.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adafactor', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 12)             │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 22)             │           286 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 382 (1.49 KB)

 Trainable params: 382 (1.49 KB)

 Non-trainable params: 0 (0.00 B)

# Retrain

⭐ **Retrain the Best Optimizer Model**

**Here, we train the best optimizer model again for more epochs. Since the previous tuning already trained each trial for 20 epochs, we use `initial_epoch=20` to tell Keras that the training is continuing from epoch 20.**

**`epochs=100` means the training will continue until epoch 100, so it will train for 80 additional epochs (from epoch 21 to 100), rather than training for another 100 epochs.**

**Additional training = 100 − 20 = 80 epochs.**

In [32]:
best_model_optimizer.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.3250 - loss: 2.3120 - val_accuracy: 0.2318 - val_loss: 17.3255
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3398 - loss: 2.2560 - val_accuracy: 0.2273 - val_loss: 18.7160
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3557 - loss: 2.1980 - val_accuracy: 0.2227 - val_loss: 20.3148
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3659 - loss: 2.1395 - val_accuracy: 0.2136 - val_loss: 21.9987
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3761 - loss: 2.0814 - val_accuracy: 0.2068 - val_loss: 23.7616
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3955 - loss: 2.0226 - val_accuracy: 0.1773 - val_loss: 25.7093
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4051 - loss: 1.9631 - val_accuracy: 0.1750 - val_loss: 27.7123
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4199 - loss: 1.9035 - val_accuracy: 0.1705 - val_loss: 29.7043
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4455 - loss: 1.8442 - val_accuracy: 0.1705 - val_loss: 31.7677
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4619 - loss: 1.7850 - val_accuracy: 0.1705 - val_loss: 33.7067
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4898 - loss: 1.7258 - val_accuracy: 0.1705 - val_loss: 35.6612
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5222 - loss: 1.6676 - val_accuracy: 0.1682 - val_loss: 37.6320
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5477 - loss: 1.6108 - val_accuracy: 0.1636 - val_loss: 39.5052
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5761 - loss: 1.5541 - val_accuracy: 0.1682 - val_loss: 41.3194
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5983 - loss: 1.4984 - val_accuracy: 0.1614 - val_loss: 43.1637
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6170 - loss: 1.4442 - val_accuracy: 0.1614 - val_loss: 44.9780
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6398 - loss: 1.3905 - val_accuracy: 0.1682 - val_loss: 46.8807
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6540 - loss: 1.3390 - val_accuracy: 0.1705 - val_loss: 48.8740
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6722 - loss: 1.2888 - val_accuracy: 0.1682 - val_loss: 51.0431
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 1.2413 - val_accuracy: 0.1659 - val_loss: 53.0714

# val_accuracy = 17%

# Now we find best no of node in the layers

**From the first training we have set default optimizer for this dataset is 'adam'** May it can in next training

In [33]:
def build_model(hp):
    model_2 = Sequential()
    
    nodes = hp.Int('nodes in each layer ', min_value = 8 , max_value = 128 )
     # step=2 can added means increment 2 step forward 8 10 12 , optinal add in nodes
    model_2.add(Input(shape=(7,)))
    
    model_2.add(Dense(units=nodes,activation='relu'))
    
    model_2.add(Dense(units=22,activation='softmax'))
    
    model_2.compile(optimizer='adamw',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

    return model_2

In [34]:
tuner_node = kt.RandomSearch(hypermodel=build_model,objective="val_accuracy",max_trials=15 ,directory="my_dir",
    project_name="helloworld",overwrite=True,)

In [35]:
tuner_node.search_space_summary()

Search space summary
Default search space size: 1
nodes in each layer  (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 128, 'step': 1, 'sampling': 'linear'}

In [36]:
tuner_node.search(X_train_scaled, y_train, epochs=20, validation_data=(X_test, y_test))

Trial 15 Complete [00h 00m 07s]
val_accuracy: 0.1818181872367859

Best val_accuracy So Far: 0.2340909093618393
Total elapsed time: 00h 01m 39s

In [37]:
tuner_node.get_best_hyperparameters()[0].values

{'nodes in each layer ': 19}

In [38]:
best_model_nodes = tuner_node.get_best_models(num_models=1)[0]
best_model_nodes.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adamw', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 19)             │           152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 22)             │           440 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 592 (2.31 KB)

 Trainable params: 592 (2.31 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
best_model_nodes.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.4642 - loss: 2.3096 - val_accuracy: 0.1818 - val_loss: 67.7089
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5778 - loss: 2.0261 - val_accuracy: 0.1750 - val_loss: 77.9886
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6352 - loss: 1.7717 - val_accuracy: 0.1705 - val_loss: 84.5074
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6977 - loss: 1.5450 - val_accuracy: 0.1432 - val_loss: 90.9584
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7437 - loss: 1.3463 - val_accuracy: 0.1432 - val_loss: 99.1152
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7812 - loss: 1.1747 - val_accuracy: 0.1432 - val_loss: 107.5937
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8097 - loss: 1.0305 - val_accuracy: 0.1477 - val_loss: 117.1091
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8267 - loss: 0.9098 - val_accuracy: 0.1591 - val_loss: 127.6576
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8483 - loss: 0.8090 - val_accuracy: 0.1705 - val_loss: 138.3531
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8580 - loss: 0.7263 - val_accuracy: 0.1795 - val_loss: 147.4535
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8722 - loss: 0.6566 - val_accuracy: 0.1932 - val_loss: 158.7845
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8852 - loss: 0.5971 - val_accuracy: 0.2091 - val_loss: 169.2999
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8915 - loss: 0.5475 - val_accuracy: 0.2114 - val_loss: 178.9657
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9023 - loss: 0.5045 - val_accuracy: 0.2091 - val_loss: 189.2812
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.4676 - val_accuracy: 0.2091 - val_loss: 199.8828
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9182 - loss: 0.4354 - val_accuracy: 0.2045 - val_loss: 208.9426
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9222 - loss: 0.4061 - val_accuracy: 0.2068 - val_loss: 218.8337
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9295 - loss: 0.3803 - val_accuracy: 0.2091 - val_loss: 227.1179
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9324 - loss: 0.3577 - val_accuracy: 0.2136 - val_loss: 237.8968
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9403 - loss: 0.3370 - val_accuracy: 0.2114 - val_loss: 247.0936

# val_accuracy = 21 %

# Now we find the best no of layers

**We modify nodes = 64 and optimizer='adam' from the above training** May it can in next training

❤️ **Build**

In [40]:
def build_model(hp):
    model_3 = Sequential()

    no_of_hidden_layers = hp.Int('no of hidden_layers',min_value=1,max_value=15 )

    model_3.add(Input(shape=(7,)))
    for i in range(no_of_hidden_layers):
    
        model_3.add(Dense(units=19,activation='relu'))
        # model_3.add(Dense(units=19,activation='relu'))
        ## Adding 2 layers inside the loop doubles the number of layers for each iteration.
    
    model_3.add(Dense(units=22,activation='softmax'))
    
    model_3.compile(optimizer='adamw',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

    return model_3

❤️ **Tune**

In [41]:
tuner_layer = kt.RandomSearch(hypermodel=build_model,objective='val_accuracy',max_trials=15,directory="my_dir",
    project_name="helloworld",overwrite=True,)

In [42]:
tuner_layer.search_space_summary()

Search space summary
Default search space size: 1
no of hidden_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 15, 'step': 1, 'sampling': 'linear'}

❤️ **Search**

In [43]:
tuner_layer.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Trial 15 Complete [00h 00m 13s]
val_accuracy: 0.21136364340782166

Best val_accuracy So Far: 0.26363635063171387
Total elapsed time: 00h 02m 27s

❤️ **Extract**

In [44]:
tuner_layer.get_best_hyperparameters()[0].values

{'no of hidden_layers': 6}

In [45]:
best_model_layers = tuner_layer.get_best_models(num_models=1)[0]
best_model_layers.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adamw', because it has 2 variables whereas the saved optimizer has 30 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 19)             │           152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 19)             │           380 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 19)             │           380 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 19)             │           380 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 19)             │           380 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 19)             │           380 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 22)             │           440 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,492 (9.73 KB)

 Trainable params: 2,492 (9.73 KB)

 Non-trainable params: 0 (0.00 B)

❤️ **Retrain**

In [46]:
best_model_layers.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.6455 - loss: 1.0464 - val_accuracy: 0.2114 - val_loss: 178.8333
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7506 - loss: 0.8018 - val_accuracy: 0.1523 - val_loss: 252.7443
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7966 - loss: 0.6350 - val_accuracy: 0.1523 - val_loss: 292.6381
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8432 - loss: 0.5063 - val_accuracy: 0.1205 - val_loss: 382.1907
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8653 - loss: 0.4239 - val_accuracy: 0.1523 - val_loss: 424.8729
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8920 - loss: 0.3480 - val_accuracy: 0.1591 - val_loss: 465.9824
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9062 - loss: 0.2996 - val_accuracy: 0.1545 - val_loss: 555.4656
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9216 - loss: 0.2560 - val_accuracy: 0.1477 - val_loss: 578.6144
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9290 - loss: 0.2247 - val_accuracy: 0.1545 - val_loss: 642.2104
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9420 - loss: 0.1930 - val_accuracy: 0.1682 - val_loss: 637.1628
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9472 - loss: 0.1750 - val_accuracy: 0.1545 - val_loss: 736.0737
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9506 - loss: 0.1637 - val_accuracy: 0.1705 - val_loss: 737.4358
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9568 - loss: 0.1506 - val_accuracy: 0.1591 - val_loss: 757.0105
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9500 - loss: 0.1539 - val_accuracy: 0.1636 - val_loss: 825.9658
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9693 - loss: 0.1171 - val_accuracy: 0.1636 - val_loss: 824.5005
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9625 - loss: 0.1147 - val_accuracy: 0.1705 - val_loss: 857.2357
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9648 - loss: 0.1131 - val_accuracy: 0.1705 - val_loss: 902.0615
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9665 - loss: 0.1000 - val_accuracy: 0.1636 - val_loss: 906.0258
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9648 - loss: 0.1026 - val_accuracy: 0.1705 - val_loss: 945.4790
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9670 - loss: 0.1001 - val_accuracy: 0.1705 - val_loss: 949.6418

# val_accuarcy = 12 % understand the concept first donot focus on val_accuary

# ⭐ Now here we hyperparmeter tunning all value 
**Also add only valuable or important hypermeters not all, like me 😁 it take time and computation power**

**Build❤️**

In [47]:
from keras.layers import Dropout, BatchNormalization
def build_model(hp):
    
    no_of_hidden_layers = hp.Int('no of hidden_layers',min_value=1,max_value=15 )
    nodes = hp.Int('nodes in each layer ', min_value = 8 , max_value = 128 )
    optimizers = hp.Choice('optimizer',['sgd','rmsprop','adam','adamw','adadelta','adagrad','adamax','nadam', 'ftrl','lion','adafactor','muon'])
    activations = hp.Choice('activation',['relu','sigmoid','tanh','softplus','softsign','selu','elu','exponential','linear','gelu','silu','swish','mish'])
    batch_normalization = hp.Boolean('batch_normalization')
    dropout = hp.Choice('dropouts',[0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]) # recommended is to 0.5 but i just wanna test
    # hp.choice take only one type of the value so u have to do 0.0 to make float not 0. faced error when u write 0. 
    model_4 = Sequential()
    
    model_4.add(Input(shape=(7,)))# Input 
    for i in range(no_of_hidden_layers):
        model_4.add(Dense(units=nodes,activation=activations))#hidden layer
        
        # agar batch_normalization hai to add nahi to add nahi aur main upar True False set kiya hai 
        #import BatchNormalization also 
        if batch_normalization: 
            model_4.add(BatchNormalization()) #batch normalization 
            
        model_4.add(Dropout(dropout))
    model_4.add(Dense(units=22,activation='softmax'))# output 
    
    model_4.compile(optimizer=optimizers,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

    return model_4

**Tune❤️**

In [48]:
tuner_final = kt.RandomSearch(hypermodel=build_model,objective='val_accuracy',max_trials=15,directory="my_dir",
    project_name="helloworld",overwrite=True, )

In [49]:
tuner_final.search_space_summary()

Search space summary
Default search space size: 6
no of hidden_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 15, 'step': 1, 'sampling': 'linear'}
nodes in each layer  (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 128, 'step': 1, 'sampling': 'linear'}
optimizer (Choice)
{'default': 'sgd', 'conditions': [], 'values': ['sgd', 'rmsprop', 'adam', 'adamw', 'adadelta', 'adagrad', 'adamax', 'nadam', 'ftrl', 'lion', 'adafactor', 'muon'], 'ordered': False}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'sigmoid', 'tanh', 'softplus', 'softsign', 'selu', 'elu', 'exponential', 'linear', 'gelu', 'silu', 'swish', 'mish'], 'ordered': False}
batch_normalization (Boolean)
{'default': False, 'conditions': []}
dropouts (Choice)
{'default': 0.0, 'conditions': [], 'values': [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], 'ordered': True}

**Search❤️**

In [50]:
tuner_final.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Trial 15 Complete [00h 00m 10s]
val_accuracy: 0.21590909361839294

Best val_accuracy So Far: 0.21590909361839294
Total elapsed time: 00h 03m 45s

In [51]:
tuner_final.get_best_hyperparameters()[0].values

{'no of hidden_layers': 2,
 'nodes in each layer ': 71,
 'optimizer': 'adam',
 'activation': 'softsign',
 'batch_normalization': True,
 'dropouts': 0.3}

In [52]:
tuner_all = tuner_final.get_best_models(num_models=1)[0]
tuner_all.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 71)             │           568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 71)             │           284 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 71)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 71)             │         5,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 71)             │           284 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 71)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 22)             │         1,584 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,832 (30.59 KB)

 Trainable params: 7,548 (29.48 KB)

 Non-trainable params: 284 (1.11 KB)

In [53]:
tuner_all.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.8972 - loss: 0.2948 - val_accuracy: 0.1818 - val_loss: 8.5424
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9085 - loss: 0.2754 - val_accuracy: 0.1909 - val_loss: 8.5381
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9125 - loss: 0.2557 - val_accuracy: 0.1886 - val_loss: 9.0079
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9159 - loss: 0.2514 - val_accuracy: 0.1591 - val_loss: 9.4397
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9057 - loss: 0.2593 - val_accuracy: 0.1841 - val_loss: 8.9942
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9227 - loss: 0.2336 - val_accuracy: 0.1659 - val_loss: 9.4147
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9273 - loss: 0.2135 - val_accuracy: 0.1636 - val_loss: 9.9269
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9233 - loss: 0.2225 - val_accuracy: 0.1886 - val_loss: 9.2595
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9227 - loss: 0.2181 - val_accuracy: 0.1909 - val_loss: 9.4357
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9261 - loss: 0.2149 - val_accuracy: 0.1727 - val_loss: 9.9663
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9205 - loss: 0.2218 - val_accuracy: 0.1886 - val_loss: 9.7046
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9159 - loss: 0.2113 - val_accuracy: 0.1864 - val_loss: 9.8226
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9256 - loss: 0.2039 - val_accuracy: 0.1932 - val_loss: 10.0787
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9341 - loss: 0.1845 - val_accuracy: 0.1977 - val_loss: 9.6551
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9273 - loss: 0.1936 - val_accuracy: 0.1955 - val_loss: 10.1873
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9312 - loss: 0.1926 - val_accuracy: 0.1932 - val_loss: 10.6609
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9318 - loss: 0.1869 - val_accuracy: 0.1795 - val_loss: 10.8551
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9398 - loss: 0.1767 - val_accuracy: 0.1841 - val_loss: 10.9856
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9381 - loss: 0.1737 - val_accuracy: 0.1977 - val_loss: 10.6262
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9352 - loss: 0.1674 - val_accuracy: 0.1955 - val_loss: 11.0651

# Val_accuracy = 14 % 
**i have try the less combinations u can try more**

**understand the cocept then move on the to get final val accuracy**


# ⭐ Here We Do important parameter and their value 
# More Improved Version

In [54]:
import keras_tuner as kt

from keras.models import Sequential
from keras.layers import Input, Dense, BatchNormalization, Dropout


def build_model(hp):

    # Hyperparameters

    no_of_hidden_layers = hp.Int("no_of_hidden_layers",min_value=1,max_value=15)

    nodes = hp.Int("nodes_in_each_layer",min_value=8,max_value=128,step=4)

    optimizer = hp.Choice("optimizer",["adam", "adamw", "rmsprop", "sgd"])

    activation = hp.Choice("activation",["relu", "gelu", "silu"])

    batch_normalization = hp.Boolean("batch_normalization")

    drop_outs = hp.Choice("drop_outs",[0.0, 0.1, 0.2, 0.3, 0.5])

    # Model

    model_5 = Sequential()

    model_5.add(Input(shape=(7,)))

    for i in range(no_of_hidden_layers):

        model_5.add(Dense(units=nodes,activation=activation))

        if batch_normalization:    
            model_5.add(BatchNormalization())

        model_5.add(Dropout(drop_outs))

    model_5.add(Dense(units=22, activation="softmax"))

    # Compile

    model_5.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model_5

In [55]:
# =========================
# Create Tuner
# =========================

tuner_f = kt.RandomSearch(
    hypermodel=build_model,
    objective="val_accuracy",
    max_trials=15,
    directory="my_dir",
    project_name="final_tuning",
    overwrite=True
)
# =========================
# Search Space Summary
# =========================

tuner_f.search_space_summary()

Search space summary
Default search space size: 6
no_of_hidden_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 15, 'step': 1, 'sampling': 'linear'}
nodes_in_each_layer (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 128, 'step': 4, 'sampling': 'linear'}
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'adamw', 'rmsprop', 'sgd'], 'ordered': False}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'gelu', 'silu'], 'ordered': False}
batch_normalization (Boolean)
{'default': False, 'conditions': []}
drop_outs (Choice)
{'default': 0.0, 'conditions': [], 'values': [0.0, 0.1, 0.2, 0.3, 0.5], 'ordered': True}

In [56]:
# =========================
# Hyperparameter Search
# =========================

tuner_f.search(
    X_train_scaled,
    y_train,
    epochs=20,
    validation_data=(X_test, y_test))

Trial 15 Complete [00h 00m 21s]
val_accuracy: 0.13409091532230377

Best val_accuracy So Far: 0.20909090340137482
Total elapsed time: 00h 03m 42s

In [57]:
# =========================
# Get Best Hyperparameters
# =========================

best_hp = tuner_f.get_best_hyperparameters()[0]


print("Best Hyperparameters:")
print(best_hp.values)

Best Hyperparameters:
{'no_of_hidden_layers': 6, 'nodes_in_each_layer': 88, 'optimizer': 'adam', 'activation': 'silu', 'batch_normalization': True, 'drop_outs': 0.3}

In [58]:
# =========================
# Get Best Model
# =========================
best_model = tuner_f.get_best_models(num_models=1)[0]

best_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 54 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 88)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 88)             │           352 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 88)             │         7,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 88)             │           352 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 88)             │         7,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 88)             │           352 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 88)             │         7,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 88)             │           352 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 88)             │         7,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 88)             │           352 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 88)             │         7,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 88)             │           352 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 22)             │         1,958 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43,934 (171.62 KB)

 Trainable params: 42,878 (167.49 KB)

 Non-trainable params: 1,056 (4.12 KB)

In [59]:
best_model.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 9s 23ms/step - accuracy: 0.3131 - loss: 2.2938 - val_accuracy: 0.1114 - val_loss: 26.2504
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4352 - loss: 1.7098 - val_accuracy: 0.1250 - val_loss: 41.5560
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5239 - loss: 1.3959 - val_accuracy: 0.1432 - val_loss: 47.0913
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5966 - loss: 1.1648 - val_accuracy: 0.1659 - val_loss: 51.9085
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6085 - loss: 1.0866 - val_accuracy: 0.1932 - val_loss: 59.9301
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6608 - loss: 0.9847 - val_accuracy: 0.2045 - val_loss: 66.9848
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6778 - loss: 0.9397 - val_accuracy: 0.1932 - val_loss: 69.3386
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6892 - loss: 0.8812 - val_accuracy: 0.3000 - val_loss: 66.1610
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7239 - loss: 0.7950 - val_accuracy: 0.2341 - val_loss: 75.5943
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7148 - loss: 0.7791 - val_accuracy: 0.2614 - val_loss: 69.1524
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7330 - loss: 0.7233 - val_accuracy: 0.1886 - val_loss: 74.3051
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7631 - loss: 0.6614 - val_accuracy: 0.2455 - val_loss: 61.1357
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7659 - loss: 0.6682 - val_accuracy: 0.1977 - val_loss: 62.8061
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7881 - loss: 0.6189 - val_accuracy: 0.2568 - val_loss: 54.7820
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7830 - loss: 0.5988 - val_accuracy: 0.2432 - val_loss: 53.7709
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8017 - loss: 0.5598 - val_accuracy: 0.2068 - val_loss: 59.9534
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8034 - loss: 0.5603 - val_accuracy: 0.2932 - val_loss: 57.5028
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8062 - loss: 0.5557 - val_accuracy: 0.2295 - val_loss: 64.4693
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8233 - loss: 0.5163 - val_accuracy: 0.2364 - val_loss: 65.6559
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8324 - loss: 0.4743 - val_accuracy: 0.2227 - val_loss: 69.9665

# val_accuracy = 25%

# Without hypertunning 14% with hypertunning 26 %

# Now i will try more things form keras tuner

In [60]:
import keras_tuner as kt

from keras.models import Sequential
from keras.layers import Input, Dense, BatchNormalization, Dropout


def build_model(hp):

    # Hyperparameters

    no_of_hidden_layers = hp.Int("no_of_hidden_layers",min_value=1,max_value=15)

    nodes = hp.Int("nodes_in_each_layer",min_value=8,max_value=128,step=4)

    optimizer = hp.Choice("optimizer",["adam", "adamw", "rmsprop", "sgd"])

    activation = hp.Choice("activation",["relu", "gelu", "silu"])

    batch_normalization = hp.Boolean("batch_normalization")

    drop_outs = hp.Choice("drop_outs",[0.0, 0.1, 0.2, 0.3, 0.5])

    # Model

    model_6 = Sequential()

    model_6.add(Input(shape=(7,)))

    for i in range(no_of_hidden_layers):

        model_6.add(Dense(units=nodes,activation=activation))

        if batch_normalization:    
            model_6.add(BatchNormalization())

        model_6.add(Dropout(drop_outs))

    model_6.add(Dense(units=22, activation="softmax"))

    # Compile

    model_6.compile(optimizer=optimizer,loss="sparse_categorical_crossentropy", metrics=["accuracy"])

    return model_6

* I have added direction to the Objective()

In [61]:

tuner_n = kt.RandomSearch( hypermodel=build_model,
    objective= kt.Objective('val_accuracy',direction='max'),
    max_trials=15,
    seed=42,
    directory="my_dir",
    project_name="final_tuning",
    overwrite=True)


tuner_n.search_space_summary()

Search space summary
Default search space size: 6
no_of_hidden_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 15, 'step': 1, 'sampling': 'linear'}
nodes_in_each_layer (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 128, 'step': 4, 'sampling': 'linear'}
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'adamw', 'rmsprop', 'sgd'], 'ordered': False}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'gelu', 'silu'], 'ordered': False}
batch_normalization (Boolean)
{'default': False, 'conditions': []}
drop_outs (Choice)
{'default': 0.0, 'conditions': [], 'values': [0.0, 0.1, 0.2, 0.3, 0.5], 'ordered': True}

In [62]:
# =========================
# Hyperparameter Search
# =========================

tuner_n.search(
    X_train_scaled,
    y_train,
    epochs=20,
    validation_data=(X_test, y_test))

Trial 15 Complete [00h 00m 17s]
val_accuracy: 0.08636363595724106

Best val_accuracy So Far: 0.2454545497894287
Total elapsed time: 00h 03m 37s

In [63]:
# =========================
# Get Best Hyperparameters
# =========================
best_hp_n = tuner_n.get_best_hyperparameters()[0].values
print(best_hp_n)

{'no_of_hidden_layers': 2, 'nodes_in_each_layer': 16, 'optimizer': 'rmsprop', 'activation': 'silu', 'batch_normalization': True, 'drop_outs': 0.1}

In [64]:
best_model_n = tuner_n.get_best_models(num_models=1)[0]

best_model_n.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 22)             │           374 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 902 (3.52 KB)

 Trainable params: 838 (3.27 KB)

 Non-trainable params: 64 (256.00 B)

In [65]:
best_model_n.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.7898 - loss: 0.8704 - val_accuracy: 0.2477 - val_loss: 95.4118
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7972 - loss: 0.8221 - val_accuracy: 0.2659 - val_loss: 100.5166
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8068 - loss: 0.7510 - val_accuracy: 0.2500 - val_loss: 107.9172
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8170 - loss: 0.7037 - val_accuracy: 0.2477 - val_loss: 114.7907
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8301 - loss: 0.6376 - val_accuracy: 0.2250 - val_loss: 120.2387
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8381 - loss: 0.6102 - val_accuracy: 0.2318 - val_loss: 123.5014
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8420 - loss: 0.5634 - val_accuracy: 0.2205 - val_loss: 128.9557
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8648 - loss: 0.5227 - val_accuracy: 0.2023 - val_loss: 133.8842
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8682 - loss: 0.5058 - val_accuracy: 0.1591 - val_loss: 140.0464
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8585 - loss: 0.4925 - val_accuracy: 0.1386 - val_loss: 147.9654
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8835 - loss: 0.4395 - val_accuracy: 0.1318 - val_loss: 154.9660
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8716 - loss: 0.4207 - val_accuracy: 0.1273 - val_loss: 161.7609
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8818 - loss: 0.3994 - val_accuracy: 0.1159 - val_loss: 171.1109
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8841 - loss: 0.3911 - val_accuracy: 0.1045 - val_loss: 185.0341
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8835 - loss: 0.3906 - val_accuracy: 0.1068 - val_loss: 184.4362
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8920 - loss: 0.3789 - val_accuracy: 0.1045 - val_loss: 195.3818
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8966 - loss: 0.3479 - val_accuracy: 0.1023 - val_loss: 191.4814
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8881 - loss: 0.3599 - val_accuracy: 0.1114 - val_loss: 197.8414
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8938 - loss: 0.3435 - val_accuracy: 0.1068 - val_loss: 210.4172
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8983 - loss: 0.3175 - val_accuracy: 0.0977 - val_loss: 222.8111

# val_accuracy = 26 %

# Now here with the different tuner "BayesianOptimization "

In [66]:
import keras_tuner as kt

from keras.models import Sequential
from keras.layers import Input, Dense, BatchNormalization, Dropout


def build_model(hp):

    # Hyperparameters

    no_of_hidden_layers = hp.Int("no_of_hidden_layers",min_value=1,max_value=15)

    nodes = hp.Int("nodes_in_each_layer",min_value=8,max_value=128,step=4)

    optimizer = hp.Choice("optimizer",["adam", "adamw", "rmsprop", "sgd"])

    activation = hp.Choice("activation",["relu", "gelu", "silu"])

    batch_normalization = hp.Boolean("batch_normalization")

    drop_outs = hp.Choice("drop_outs",[0.0, 0.1, 0.2, 0.3, 0.5])

    # Model

    model_7 = Sequential()

    model_7.add(Input(shape=(7,)))

    for i in range(no_of_hidden_layers):

        model_7.add(Dense(units=nodes,activation=activation))

        if batch_normalization:    
            model_7.add(BatchNormalization())

        model_7.add(Dropout(drop_outs))

    model_7.add(Dense(units=22, activation="softmax"))

    # Compile

    model_7.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model_7

* Here I have do the intial point that tuner take information from the 5 intial points
* 
* beta controls the amount of exploration (default=2.6)
* Low beta  → focuses more on promising combinations (e.g., 0.1, 0.5, 1.0)
* High beta → tries more new/uncertain combinations (e.g., 2.6, 5.0, 9.0)
* Exploration simply means:
  Trying new hyperparameter combinations that the tuner has not tried much before.

Adam + 64 neurons → already looks good 🎯

Exploration → "Let me also try..."
RMSprop + 128 neurons
SGD + 32 neurons
AdamW + 96 neurons

In [67]:
tuner_b = kt.BayesianOptimization( hypermodel=build_model,
    objective= kt.Objective('val_accuracy',direction='max'),
    num_initial_points=5,
    max_trials=15,
    seed=42,
    directory="my_dir",
    project_name="final_tuning",
    overwrite=True)


tuner_b.search_space_summary()

Search space summary
Default search space size: 6
no_of_hidden_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 15, 'step': 1, 'sampling': 'linear'}
nodes_in_each_layer (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 128, 'step': 4, 'sampling': 'linear'}
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'adamw', 'rmsprop', 'sgd'], 'ordered': False}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'gelu', 'silu'], 'ordered': False}
batch_normalization (Boolean)
{'default': False, 'conditions': []}
drop_outs (Choice)
{'default': 0.0, 'conditions': [], 'values': [0.0, 0.1, 0.2, 0.3, 0.5], 'ordered': True}

In [68]:
# =========================
# Hyperparameter Search
# =========================
tuner_b.search(
    X_train_scaled,
    y_train,
    epochs=20,
    validation_data=(X_test, y_test))

Trial 15 Complete [00h 00m 19s]
val_accuracy: 0.052272725850343704

Best val_accuracy So Far: 0.16818182170391083
Total elapsed time: 00h 04m 03s

In [69]:
best_hp_b = tuner_b.get_best_hyperparameters()[0].values
print(best_hp_b)

{'no_of_hidden_layers': 2, 'nodes_in_each_layer': 24, 'optimizer': 'rmsprop', 'activation': 'silu', 'batch_normalization': True, 'drop_outs': 0.1}

In [70]:
best_model_b = tuner_b.get_best_models(num_models=1)[0]

best_model_b.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 24)             │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 24)             │            96 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 24)             │           600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 24)             │            96 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 22)             │           550 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,534 (5.99 KB)

 Trainable params: 1,438 (5.62 KB)

 Non-trainable params: 96 (384.00 B)

In [71]:
best_model_b.fit(X_train_scaled,y_train,epochs=20,validation_data=(X_test,y_test))

Epoch 1/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.9244 - loss: 0.2579 - val_accuracy: 0.1750 - val_loss: 285.9424
Epoch 2/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9341 - loss: 0.2394 - val_accuracy: 0.1750 - val_loss: 287.0837
Epoch 3/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9443 - loss: 0.2069 - val_accuracy: 0.1636 - val_loss: 306.5996
Epoch 4/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9420 - loss: 0.2121 - val_accuracy: 0.1568 - val_loss: 316.2169
Epoch 5/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9369 - loss: 0.2139 - val_accuracy: 0.1591 - val_loss: 328.5249
Epoch 6/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9449 - loss: 0.1988 - val_accuracy: 0.1455 - val_loss: 343.7960
Epoch 7/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9517 - loss: 0.1814 - val_accuracy: 0.1364 - val_loss: 358.3094
Epoch 8/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9460 - loss: 0.1919 - val_accuracy: 0.1318 - val_loss: 369.0234
Epoch 9/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9472 - loss: 0.1709 - val_accuracy: 0.1318 - val_loss: 390.0430
Epoch 10/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9449 - loss: 0.1773 - val_accuracy: 0.1273 - val_loss: 403.6994
Epoch 11/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9489 - loss: 0.1639 - val_accuracy: 0.1182 - val_loss: 410.2762
Epoch 12/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9443 - loss: 0.1663 - val_accuracy: 0.1295 - val_loss: 402.1029
Epoch 13/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9506 - loss: 0.1703 - val_accuracy: 0.1205 - val_loss: 420.7888
Epoch 14/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9483 - loss: 0.1599 - val_accuracy: 0.1136 - val_loss: 442.5491
Epoch 15/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9500 - loss: 0.1720 - val_accuracy: 0.1114 - val_loss: 466.1030
Epoch 16/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9511 - loss: 0.1599 - val_accuracy: 0.1045 - val_loss: 477.9183
Epoch 17/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9472 - loss: 0.1667 - val_accuracy: 0.0841 - val_loss: 492.0716
Epoch 18/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9557 - loss: 0.1385 - val_accuracy: 0.0841 - val_loss: 482.9002
Epoch 19/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9540 - loss: 0.1480 - val_accuracy: 0.0864 - val_loss: 490.9560
Epoch 20/20
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9597 - loss: 0.1386 - val_accuracy: 0.0795 - val_loss: 515.5493

# val_accuracy 7 % 😁 I have not try more combination due to time and computation cost

# Now the "Hyperband "

In [72]:
import keras_tuner as kt

from keras.models import Sequential
from keras.layers import Input, Dense, BatchNormalization, Dropout


def build_model(hp):

    # Hyperparameters

    no_of_hidden_layers = hp.Int("no_of_hidden_layers",min_value=1,max_value=15)

    nodes = hp.Int("nodes_in_each_layer",min_value=8,max_value=128,step=4)

    optimizer = hp.Choice("optimizer",["adam", "adamw", "rmsprop", "sgd"])

    activation = hp.Choice("activation",["relu", "gelu", "silu"])

    batch_normalization = hp.Boolean("batch_normalization")

    drop_outs = hp.Choice("drop_outs",[0.0, 0.1, 0.2, 0.3, 0.5])

    # Model

    model_8 = Sequential()

    model_8.add(Input(shape=(7,)))

    for i in range(no_of_hidden_layers):

        model_8.add(Dense(units=nodes,activation=activation))

        if batch_normalization:    
            model_8.add(BatchNormalization())

        model_8.add(Dropout(drop_outs))

    model_8.add(Dense(units=22, activation="softmax"))

    # Compile

    model_8.compile(
        optimizer=optimizer,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model_8

* it donesnot have the max_trail it have epochs and it make combination like this
  
        #Adam    + 32  nodes
        #Adam    + 64 nodes
        #Adam    + 96 nodes
        #Adam    + 128 nodes
  
        #SGD     + 32 nodes
        #SGD     + 64 nodes
        #SGD     + 96 nodes
        #SGD     + 128 nodes

        #RMSprop + 32 nodes
        #RMSprop + 64 nodes
        #RMSprop + 96 nodes
        #RMSprop + 128 nodes

* hyperband_iteration menas how many combination it try :
* 1st iteration:
*  
    Try configurations
   
    → Adam + 32
   
    → SGD + 64
   
    → RMSprop + 128
   
    → ... 🏆

* 2nd iteration:
 
    Run Hyperband again
  
    → Try other configurations
  
    → Compare results
  
    → ... 🏆

In [77]:
tuner_h = kt.Hyperband(
    hypermodel=build_model,
    objective='val_accuracy',
    max_epochs=15,
    factor=5,
    hyperband_iterations=10 # 
)

Reloading Tuner from ./untitled_project/tuner0.json

In [78]:
# =========================
# Hyperparameter Search
# =========================
tuner_h.search(
    X_train_scaled,
    y_train,
    epochs=1,
    validation_data=(X_test, y_test))

Trial 49 Complete [00h 00m 16s]
val_accuracy: 0.03181818127632141

Best val_accuracy So Far: 0.20000000298023224
Total elapsed time: 00h 11m 03s

Search: Running Trial #50

Value             |Best Value So Far |Hyperparameter
13                |2                 |no_of_hidden_layers
128               |100               |nodes_in_each_layer
adam              |rmsprop           |optimizer
relu              |relu              |activation
True              |False             |batch_normalization
0.5               |0                 |drop_outs
7                 |7                 |tuner/epochs
0                 |3                 |tuner/initial_epoch
1                 |2                 |tuner/bracket
0                 |1                 |tuner/round

Epoch 1/7

KeyboardInterrupt:

# And all steps same 
# I have stopped the training of the  best combination cause,i have less patience level

# Just Understand the Concept and how to use the keras tuner works